database.path=${user.home}/city-service-db
database.user=sa
database.password=

jpa.dialect=org.hibernate.dialect.H2Dialect
jpa.ddl-auto=validate
jpa.show-sql=false
jpa.format-sql=false

database.migration.locations=classpath:db/migration
database.migration.baseline-on-migrate=true
